apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-records-app
  labels:
    app: student-records-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-records-app
  template:
    metadata:
      labels:
        app: student-records-app
    spec:
      containers:
        - name: student-records-app
          image: delphinemuke3/student-records-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root_password"
            - name: DB_NAME
              value: "students_db"
---
apiVersion: v1
kind: Service
metadata:
  name: student-records-service
spec:
  selector:
    app: student-records-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
